Google Maps API
carolyn-wang/friendly pull request #27
Opened 2022-07-05 18:32 UTC by carolyn-wang

* Added map that displays current user's location, nearest other users, and nearest locations
* Can retrieve and save user's current device location
          * As backup, retrieve user's most recent location from database
* Can set custom markers and custom map zoom settings
* Uses [MapView](https://developers.google.com/android/reference/com/google/android/gms/maps/MapView) instead of [MapFragment or SupportMapFragment](https://stackoverflow.com/questions/29919534/differences-between-mapview-mapframent-and-supportmapfragment/43667906#43667906) for better control over fragment lifecycle

Future Changes:
* Will add custom function calls to only display current user, matched user, and nearest location on map after clicking button
* Need to resolve lifecycle conflicts between MapFragment and HangoutsFragment after merging (code not updated at the moment so can't fix)

<img width="354" alt="Screen Shot 2022-07-05 at 11 19 37 AM" src="https://user-images.githubusercontent.com/69578355/177392729-6fc8c154-2e75-4e23-8483-4c374d8183e2.png">

2022-07-06 19:54 UTC, NavinMahabir requested changes

2022-07-06 19:54 UTC, NavinMahabir commented on .idea/deploymentTargetDropDown.xml
> +<?xml version="1.0" encoding="UTF-8"?>
see if you can remove this file from the commit, not needed

2022-07-06 19:54 UTC, NavinMahabir commented on .idea/misc.xml
> +        <entry key="app/src/main/res/layout/activity_google_maps.xml" value="0.5286458333333334" />
same with these changes

2022-07-06 19:54 UTC, NavinMahabir commented on app/src/main/AndroidManifest.xml
> -<?xml version="1.0" encoding="utf-8"?>
Why are you removing this manifest file? Do you have two?

2022-07-06 19:54 UTC, NavinMahabir commented on app/src/main/java/com/example/friendly/fragments/MapFragment.java
> +        return getCurrentUserParseLocation();
seems redundant that we are fetching the location from our backend if we already have the location on line 134

2022-07-06 19:54 UTC, NavinMahabir commented on app/src/main/java/com/example/friendly/fragments/MapFragment.java
> +    public ParseGeoPoint getSaveCurrentUserDeviceLocation() {
`getSave` seems kinda awkward, how about `updateCurrentUserDeviceLocation`?

2022-07-06 19:54 UTC, NavinMahabir commented on app/src/main/java/com/example/friendly/fragments/MapFragment.java
> +        return getCurrentUserParseLocation();
we also aren't guaranteed that we will be fetching the latest location since the upload could be slow

2022-07-06 19:54 UTC, NavinMahabir commented on app/src/main/java/com/example/friendly/MapsActivity.java
> +                getCurrentLocation();
what's the point of getting the location if we don't use it?

2022-07-06 19:54 UTC, NavinMahabir commented on app/src/main/java/com/example/friendly/objects/Preference.java
is it possible that we can delete this?

2022-07-06 19:54 UTC, NavinMahabir commented on app/src/main/java/com/example/friendly/fragments/match/MatchFragment.java
> +    private Activity mActivity;
I don't see why we need to hold on to the activity

2022-07-06 19:54 UTC, NavinMahabir commented on app/src/main/java/com/example/friendly/fragments/MapFragment.java
> +        showCurrentUserInMap(googleMap);
Instead of passing the map everywhere, would it make sense to save it as a class variable?

2022-07-07 15:35 UTC, NavinMahabir commented on .gitignore
> +app/src/main/AndroidManifest.xml
you should remove this

2022-07-07 15:35 UTC, NavinMahabir commented on app/src/main/java/com/example/friendly/NavigationUtils.java
> +//        Fragment hangoutHistoryFragment = new HangoutsFragment().newInstance(user);
these commented out lines shouldn't be committed

2022-07-07 15:36 UTC, NavinMahabir commented on app/src/main/java/com/example/friendly/NavigationUtils.java
> +        ft.replace(R.id.flContainer, mapFragment)
can inline this mapFragment construction

2022-07-07 15:38 UTC, NavinMahabir commented on app/src/main/java/com/example/friendly/fragments/HangoutsFragment.java
> +@Deprecated
what's the reason for deprecating this? what should readers be using instead?

2022-07-07 15:39 UTC, NavinMahabir commented on app/src/main/java/com/example/friendly/fragments/HangoutsFragment.java
> +//        query.queryHangouts(adapter, queryConditions);
understand that this class is deprecated, but this commented out code still shouldn't really be committed

2022-07-07 23:28 UTC, carolyn-wang commented on app/src/main/java/com/example/friendly/fragments/HangoutsFragment.java
> +//        query.queryHangouts(adapter, queryConditions);
Sorry, there's a lot of commented out code for HangoutsFragment and HangoutsHistoryFragment since I changed the code and database for them in another PR, and that PR was still pending review at the time. 

Since the querying functions for HangoutsFragment (in this "places" branch) are no longer up to date with the database, everything hangouts-related crashes in this branch, so I commented it all out. I know it's bad to commit commented code. In the future is there some way for me to rebase or move changes from another branch so I don't have to comment out code?

2022-07-11 20:56 UTC, NavinMahabir approved these changes
I think DisplayUtils should be removed from this PR since it's not related. Otherwise, clear to squash & merge :)

2022-07-11 21:30 UTC, merged