Preference options
carolyn-wang/friendly pull request #44
Opened 2022-07-13 18:33 UTC by carolyn-wang

Preference poll activity for when users sign up (LoginActivity >> SignUpActivity >> PreferencesActivity) or when users want to change preferences ( (LoginActivity >> MainActivity (Profile Fragment) >> PreferencesActivity)
* RecyclerView adapter inflates either a RadioGroup card or Checkbox card, depending on the poll card's position
* Saves user clicks in background and keeps preferences updated upon opening and closing fragment
* Dynamically adds rows on poll card, depending on how many options are available
* Preference object stores database key, question, and String[] of question options

<img width="257" alt="Screen Shot 2022-07-13 at 11 28 33 AM" src="https://user-images.githubusercontent.com/69578355/178805517-2e5caf03-f9b9-4878-abe8-e22c5c692f11.png">

2022-07-14 01:39 UTC, NavinMahabir requested changes
I am seeing duplicate changes here that were already made in #43, please rebase and insure that your main is up to date

2022-07-14 21:44 UTC, NavinMahabir commented on app/src/main/res/layout/item_poll_card_checkbox.xml
> +    </LinearLayout>
Can we make this without the linearlayout?

2022-07-14 21:44 UTC, NavinMahabir commented on app/src/main/java/com/example/friendly/activities/SignUpActivity.java
> +import com.parse.Parse;
is this import needed?

2022-07-14 21:44 UTC, NavinMahabir commented on app/src/main/java/com/example/friendly/adapters/PreferencesAdapter.java
> +        ParseUser.getCurrentUser().put(preferenceKey, index);
just for my understanding, does the put operate quickly? Like it won't risk stalling the UI?

2022-07-14 23:07 UTC, carolyn-wang commented on app/src/main/java/com/example/friendly/adapters/PreferencesAdapter.java
> +        ParseUser.getCurrentUser().put(preferenceKey, index);
It doesn't stall my UI when I test it at least? I can't find anything online about the speed of ParseUser.put()

2022-07-14 23:09 UTC, carolyn-wang commented on app/src/main/res/layout/item_poll_card_checkbox.xml
> +    </LinearLayout>
I'm dynamically adding rows to this LinearLayout section through my PreferencesAdapter, so LinearLayout was the best way I could figure out for adding additional rows, one below another. 

Currently looking into other ways right now

2022-07-15 17:04 UTC, NavinMahabir commented on app/src/main/java/com/example/friendly/adapters/PreferencesAdapter.java
> +            if (getItemViewType() == 0) {
update this to use the constants you've defined instead of `0`

2022-07-15 17:04 UTC, NavinMahabir commented on app/src/main/java/com/example/friendly/adapters/PreferencesAdapter.java
> +        ParseUser.getCurrentUser().put(preferenceKey, index);
Ok, it's probably fine then, but something to look out for in case you do see things are going slow

2022-07-15 17:58 UTC, NavinMahabir approved these changes
Rest looks good to me, please address the last few comments and then you are good to merge 😊

2022-07-15 17:58 UTC, NavinMahabir commented on app/src/main/res/layout/item_poll_card_checkbox.xml
> +    </LinearLayout>
Ok, this makes sense to me. You can keep it as is

2022-07-15 21:18 UTC, merged